### ISSUE TITLE
Host configuration seems to be ignored and defaults to the Neon hosted instance

### ISSUE THREAD

**Issue by AmateurAcademic** [NeonGeckoCom/neon-tts-plugin-larynx_server#4]
For example, I define the host and the port [here](https://github.com/AmateurAcademic/TTS-wakeword-generator/blob/98aad8ffad43f6f8bd942c9eef2da960e07ec887/TTS_wakeword_data_generator.py#L97):

```
config_larynx = {
        "host": larynx_host,
        "voice": voice,
        "vocoder": "hifi_gan/universal_large",
    }
```

When I run the script with let's say a host of: `"127.0.0.1:5002"`, I see nothing in the logs of my local instance, however when I run TTS via the front end of my local instance, I see the logs reporting the usage. 

Also I do get an output of the correct TTS files.

Either I am doing something totally wrong (which is always a possibility), there are no logs in Larynx when you run it via this script(?), or the plugin is ignoring the host config and using the default (Neon) instance.

**Comment by NeonDaniel** [comment]
Hmm. You should need to prefix the host with `http://` but I'm not sure why you got an output at all unless the config isn't being handled correctly. Could you verify the config is being parsed correctly? Either a breakpoint or logging `tts.url` should identify the URL in your script https://github.com/AmateurAcademic/TTS-wakeword-generator/blob/98aad8ffad43f6f8bd942c9eef2da960e07ec887/TTS_wakeword_data_generator.py#L104

**Comment by AmateurAcademic** [comment]
Hey @NeonDaniel, thanks for following up! So it seems if you don't add in the `http://` in the host, the plugin falls back to the default server. That was the problem. Thanks!
