### ISSUE TITLE
unable to install: No matching distribution found

### ISSUE THREAD

**Issue by Byolock** [NeonGeckoCom/neon-tts-plugin-larynx_server#6]
I get the following output when running `pip install neon-tts-plugin-larynx-server` :
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement neon-tts-plugin-larynx-server (from versions: none)
ERROR: No matching distribution found for neon-tts-plugin-larynx-server
```

platform i tested on is a raspberry pi 4 with the 64-bit OS.

**Comment by NeonDaniel** [comment]
This package hasn't yet been published to PyPI (https://github.com/NeonGeckoCom/neon-tts-plugin-larynx_server/issues/1).
You can install from git (if `git` isn't installed, you might need to `sudo apt install git`):
```
pip install git+https://github.com/NeonGeckoCom/neon-tts-plugin-larynx_server
```

I didn't realize the README listed PyPI installation instructions though, thanks for the ping!

**Comment by NeonDaniel** [comment]
Published to PyPI, please reopen or open a new issue if installation errors persist
